# Site settings
name: Cattamoo
email: ouob77@kakao.com
url: https://cattamoo.github.io/
description: "A blog and a portfolio"
author: "author"
title: "CattamooFolio"
permalink: /:categories/:year/:title
baseurl: /
favicon: /img/favicon.ico

# social
github:
  username: Cattamoo

instagram:
  username: yjovos2